use std::cell::Cell;
use std::fmt::Display;

use jni::JNIEnv;
use jni::objects::{JObject, JValue};

pub use jni::errors::Error as JniError;
pub type Result<T = ()> = std::result::Result<T, JniError>;

/// Rust wrapper around the `CallbackInfo` passed to a Mixin `@Inject` handler.
/// The JNI wrapper generated by `#[inject_macro::inject]` wraps its third
/// argument (jobject) in this struct and forwards it to the user function.
pub struct CallbackInfo<'local> {
    inner: JObject<'local>,
}

impl<'local> CallbackInfo<'local> {
    /// # Safety
    /// `inner` is a local ref valid only within the scope of the JNI function
    /// call. Normally this is called only from inject-macro-generated code.
    pub unsafe fn from_jobject(inner: JObject<'local>) -> Self {
        CallbackInfo { inner }
    }

    /// Calls `CallbackInfo.cancel()`. If the corresponding `@Inject` is not
    /// `cancellable = true`, the Java side throws `IllegalStateException`,
    /// which propagates as `JniError::JavaException`.
    pub fn cancel(&self) -> Result<()> {
        with_env(|env| {
            env.call_method(&self.inner, "cancel", "()V", &[])?;
            Ok(())
        })
    }
}

thread_local! {
    static CURRENT_ENV: Cell<*mut jni::sys::JNIEnv> = const { Cell::new(std::ptr::null_mut()) };
}

/// RAII guard created only inside the JNI wrapper generated by
/// `#[inject_macro::inject]`. Until dropped, it stores the current JNIEnv
/// pointer in a thread-local so wrapper functions like `api::println` can
/// obtain the env without taking it as an argument.
pub struct EnvGuard {
    prev: *mut jni::sys::JNIEnv,
}

impl EnvGuard {
    /// # Safety
    /// `env` is valid only within the lifetime of the calling JNI function.
    /// Do not create any other reference to env until this guard is dropped.
    pub unsafe fn enter(env: &mut JNIEnv) -> Self {
        let raw = env.get_raw();
        let prev = CURRENT_ENV.with(|c| c.replace(raw));
        EnvGuard { prev }
    }
}

impl Drop for EnvGuard {
    fn drop(&mut self) {
        CURRENT_ENV.with(|c| c.set(self.prev));
    }
}

fn with_env<R>(f: impl FnOnce(&mut JNIEnv) -> R) -> R {
    let raw = CURRENT_ENV.with(|c| c.get());
    assert!(
        !raw.is_null(),
        "api::* called outside of a #[inject] function"
    );
    // SAFETY: EnvGuard has registered the env of the JNI function currently
    // active on this thread.
    let mut env = unsafe { JNIEnv::from_raw(raw).expect("invalid JNIEnv pointer") };
    f(&mut env)
}

/// Calls `System.out.println(value.to_string())` over JNI.
pub fn println<T: Display>(value: T) -> Result<()> {
    let s = value.to_string();
    with_env(|env| -> Result<()> {
        let jstr = env.new_string(&s)?;
        let system_cls = env.find_class("java/lang/System")?;
        let out = env.get_static_field(&system_cls, "out", "Ljava/io/PrintStream;")?;
        let out_obj = out.l()?;
        env.call_method(
            &out_obj,
            "println",
            "(Ljava/lang/String;)V",
            &[JValue::from(&jstr)],
        )?;
        Ok(())
    })
}
